### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by lduh** [jupyterday-atlanta-2016/jupyterday-atlanta-2016.github.io#2]
Hi, I have a question I'd like to ask the community about...

> ## PROTIP: delete this before you submit!
> 
> Hi there! Issues created here should be about general, **public** questions about JupyterDay Atlanta 2016
> 
> > _Private communications can be addressed directly to [tony.fast@continuum.io](mailto:tony.fast@continuum.io)!_
> 
> **New proposals** should be created as issue on the [ proposals](https://github.com/jupyterday-atlanta-2016/proposals/issues/new) repository!
> 
> Examples
> - JupyterDay Atlanta 2016
>   - traveling to the event
>   - lodging and transportation
> - Atlanta
> - Jupyter!
> ## PROTIP: We might use this issue as part of the [FAQ](https://jupyterday-atlanta-2016.github.io/#FAQ)

**Comment by lduh** [comment]
QA

**Comment by tonyfast** [comment]
Yay.  Thanks.
